# Generated by Django 3.1.4 on 2022-05-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='departs',
        ),
        migrations.RemoveField(
            model_name='school',
            name='getin',
        ),
        migrations.AddField(
            model_name='department',
            name='schools',
            field=models.ManyToManyField(related_name='departs', to='log.School'),
        ),
        migrations.RemoveField(
            model_name='department',
            name='admits',
        ),
        migrations.AddField(
            model_name='department',
            name='admits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.admission', verbose_name='入學管道'),
        ),
    ]
