# Generated by Django 3.1.4 on 2022-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20220511_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d_file',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='說明檔案'),
        ),
    ]
