# Generated by Django 3.1.4 on 2022-05-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20220511_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='d_file',
        ),
    ]
