# Generated by Django 3.1.4 on 2022-05-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_remove_department_d_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='aflie',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='入學管道說明檔案'),
        ),
        migrations.AddField(
            model_name='department',
            name='dflie',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='科系/班級說明檔案'),
        ),
        migrations.AddField(
            model_name='school',
            name='sflie',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='學校說明檔案'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='adesc',
            field=models.TextField(max_length=2048, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admit',
            field=models.CharField(max_length=256, verbose_name='入學管道'),
        ),
        migrations.AlterField(
            model_name='department',
            name='ddesc',
            field=models.TextField(max_length=2048, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='department',
            name='depart',
            field=models.CharField(max_length=256, verbose_name='科系/班級名稱'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=256, verbose_name='學校名稱'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sdesc',
            field=models.TextField(max_length=2048, verbose_name='說明'),
        ),
    ]
