# Generated by Django 3.1.4 on 2022-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20220514_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdesc', models.TextField(max_length=2048, verbose_name='網站首頁說明')),
            ],
        ),
    ]
