# Generated by Django 3.1.4 on 2022-05-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='htitle',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='網站消息標題'),
        ),
        migrations.AlterField(
            model_name='home',
            name='hdesc',
            field=models.TextField(max_length=2048, verbose_name='網站消息內容'),
        ),
    ]
