# Generated by Django 3.1.4 on 2022-05-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20220514_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='htitle',
            field=models.CharField(max_length=256, verbose_name='網站消息標題'),
        ),
    ]
