# Generated by Django 3.1.4 on 2022-05-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20220514_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='aflie',
            new_name='afile',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dflie',
            new_name='dfile',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='sflie',
            new_name='sfile',
        ),
    ]
