# Generated by Django 3.1.4 on 2022-05-15 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20220514_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='htime',
            field=models.DateField(default=datetime.date.today, verbose_name='新增時間'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='adesc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='department',
            name='ddesc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sdesc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='說明'),
        ),
    ]
