# Generated by Django 3.1.4 on 2022-05-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20220516_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='schools',
            field=models.ManyToManyField(related_name='departs', to='log.School', verbose_name='學校'),
        ),
    ]
