# Generated by Django 3.1.4 on 2022-05-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20220516_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='alink1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='入學方法參考網址(先選填)'),
        ),
        migrations.AddField(
            model_name='admission',
            name='alink2',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='入學方法參考網址(後選填)'),
        ),
        migrations.AddField(
            model_name='department',
            name='dlink1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='科系/班級參考網址(先選填)'),
        ),
        migrations.AddField(
            model_name='department',
            name='dlink2',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='科系/班級參考網址(後選填)'),
        ),
        migrations.AddField(
            model_name='school',
            name='slink1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='學校參考網址(先選填)'),
        ),
        migrations.AddField(
            model_name='school',
            name='slink2',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='學校參考網址(後選填)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='adesc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='入學方法說明(選填)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='admit',
            field=models.CharField(max_length=256, verbose_name='入學方法'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='afile',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='入學方法說明檔案(選填)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='admits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.admission', verbose_name='入學方法'),
        ),
        migrations.AlterField(
            model_name='department',
            name='ddesc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='說明(選填)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dfile',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='科系/班級說明檔案(選填)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sdesc',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='學校說明(選填)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sfile',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='學校說明檔案(選填)'),
        ),
    ]
