# Generated by Django 3.1.4 on 2022-05-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20220529_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='afile',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='入學方法說明檔案Google雲端網址(選填)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='alink1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='入學方法參考網址1(先選填)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='alink1name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='入學方法參考網址名稱1(先選填)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='alink2',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='入學方法參考網址2(後選填)'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='alink2name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='入學方法參考網址名稱2(後選填)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dfile',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='科系/班級說明檔案Google雲端網址(選填)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dlink1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='科系/班級參考網址1(先選填)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dlink1name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='科系/班級參考網址名稱1(先選填)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dlink2',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='科系/班級參考網址2(後選填)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dlink2name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='科系/班級參考網址名稱2(後選填)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sfile',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='學校說明檔案Google雲端網址(選填)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slink1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='學校參考網址1(先選填)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slink1name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='學校參考網址名稱1(先選填)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slink2',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='學校參考網址2(後選填)'),
        ),
        migrations.AlterField(
            model_name='school',
            name='slink2name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='學校參考網址名稱2(後選填)'),
        ),
    ]
