# Generated by Django 3.1.4 on 2022-06-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20220529_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='hlink1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='消息參考網址1(先選填)'),
        ),
        migrations.AddField(
            model_name='home',
            name='hlink1name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='消息參考網址名稱1(先選填)'),
        ),
        migrations.AddField(
            model_name='home',
            name='hlink2',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='消息參考網址2(後選填)'),
        ),
        migrations.AddField(
            model_name='home',
            name='hlink2name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='消息參考網址名稱2(後選填)'),
        ),
    ]
